# Generated by Django 4.2.3 on 2023-09-03 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Ismi')),
                ('surname', models.CharField(max_length=128, verbose_name='Familiyasi')),
                ('phone', models.CharField(max_length=128, verbose_name='Tel:')),
                ('img', models.ImageField(upload_to='doctor_img', verbose_name='Rasmi')),
                ('info', models.TextField(verbose_name='Doctor haqida qisqacha')),
                ('email', models.EmailField(max_length=254, verbose_name='Email manzili')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': '1. Doctors',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('info', models.TextField()),
                ('icon', models.ImageField(upload_to='icon_img')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=128)),
                ('pr', models.IntegerField(blank=True, editable=False, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctor')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.services')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.position', verbose_name='Lavozimi'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profession', verbose_name='Mutaxassisligi'),
        ),
        migrations.CreateModel(
            name='Doctime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('free', models.BooleanField(default=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctor')),
            ],
        ),
    ]
